jwt:
    jwtExpirationInMs: 18000000
    secret: javainuse
server:
    port: 8443
    ssl:
        enabled: true
        key-store: src/main/resources/reactivestax.jks
        key-store-password: firew0rks
        key-store-type: PKCS12
spring:
    security:
        oauth2:
            client:
                # From OIDC app
                clientId: 0oa5jslgqlVtWu4UD5d6
                clientSecret: VMMRFWgN247UkB8hDGr2hHer8eIBD429G5gyNd0d
                # From Authorization Server's metadata
                accessTokenUri: https://dev-30002792.okta.com/oauth2/default/v1/token
                userAuthorizationUri: https://dev-30002792.okta.com/oauth2/default/v1/authorize
                clientAuthenticationScheme: form
                scope: openid profile email
            resource:
                # from your Auth Server's metadata, check .well-known/openid-configuration if not in .well-known/oauth-authorization-server
                userInfoUri: https://dev-30002792.okta.com/oauth2/default/v1/userinfo
    datasource:
        password: jhvjv
        url: jdbc:postgresql://localhost:5432/userdb
        username: kunal
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
